### PR TITLE
Adds efinity info

### PR DESCRIPTION
**Pull request by leonardocustodio**

### CODE REVIEW

**Review by octo-gone — CHANGES_REQUESTED** [review]
Hello!
Please add an entry to [archives.json](https://github.com/subsquid/archive-registry/blob/main/archives.json) file, specify links to archive and explorer there. Another thing, run `npm run gen-types` to update types inside [chains.ts](https://github.com/subsquid/archive-registry/blob/main/src/chains.ts). Last but not least, add icon of net to the special [folder](https://github.com/subsquid/archive-registry/tree/main/ui/logos/networks), recommended size is 512x512 px.

**Comment by octo-gone** [comment]
Hi, there are some changes, fetch and merge repo before everything

**Comment by leonardocustodio** [comment]
There you go, hope that's correct :)

**Comment by octo-gone** [comment]
Everything is good, but I thought that you provide your own archive. Okay, that is not a problem, it will take some time until archive will be ready. Thank you for your work!

**Comment by leonardocustodio** [comment]
Ah sorry, that was the reason I had only updated the networks file and not the others. Thought you guys would update it when the archive was ready. I sent @RaekwonIII the link to the archive nodes.

**Comment by octo-gone** [comment]
I am sorry too, small misunderstanding. 😁

**Review by octo-gone — APPROVED** [review]

**Pull request merged**
