### PR TITLE
Unique network blockchains archives: opal, quartz, unique.

### PR DESCRIPTION
**Pull request by sswebcoder**

### CODE REVIEW

**Comment by octo-gone** [comment]
Hello, thank you for you request. Please complete the following tasks: 

- make sure that archives completely processed;
- remove explorer URL field (if you don't have one);
- add entries to [networks.json](https://github.com/subsquid/archive-registry/blob/main/networks.json) (or update entries);
- provide one rpc endpoint for each network to check current sync status.

**Comment by octo-gone** [comment]
I also suggest you to increase the quality of the icons to 512 pixels on each side.

**Review by octo-gone — CHANGES_REQUESTED** [review]

**Comment by sswebcoder** [comment]
@octo-gone can you check again? I have fixed all points what you highlighted.

If something looks wrong please let me know.

**Review by octo-gone — APPROVED** [review]

**Comment by octo-gone** [comment]
Everything is nice and clean, great job!

**Pull request merged**
