### PR TITLE
new registry

### PR DESCRIPTION
**Pull request by belopash**

### CODE REVIEW

**Comment by dzhelezov** [comment]
@aintnomoreloyalty pla check

**Comment by aintnomoreloyalty** [comment]
Hi, we also should add description field to each network

**Comment by aintnomoreloyalty** [comment]
Hi, we also should add description field to each network

**Comment by dzhelezov** [comment]
for moobeam, moonriver, shiden, astar -> go for moobeam-beta, moonriver-beta, astar-beta, shiden-beta archives

**Pull request merged**
